### PR TITLE
Fix bug get config file

### PR DESCRIPTION
**Pull request by dominuskernel**

### CODE REVIEW

**Comment by controversial** [comment]
@skyrpex can this be merged?

**Comment by skyrpex** [comment]
Sure, thanks!

**Comment by controversial** [comment]
@skyrpex Can we also get a new release (`0.2.1`) so that we can update the package with this change 🙏

**Comment by skyrpex** [comment]
Forgot that... haha

**Comment by controversial** [comment]
Thanks, that would be great 😀

**Comment by skyrpex** [comment]
Meanwhile, I suggest to use the atom-linter's official package: https://atom.io/packages/linter-pug

**Pull request merged**
